language: node_js
sudo: false
notifications:
  email: false
node_js:
  - "10" # stable
  - "8" # LTS
  - "6" # maintenance
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
